// Get all comments
###
GET http://localhost:8081/comment/getAll
Content-Type: application/json

// Create new comment
###
POST http://localhost:8081/comment/
Content-Type: application/json

{
  "userId": "1",
  "comment": "Great station",
  "station": "Blue",
  "commentId": "1"
}

// Edit comment by id (_id)
###
PUT http://localhost:8081/comment/editComment/660adeb96ed30e4a5d346524
Content-Type: application/json 

{
    "_id": "660adeb96ed30e4a5d346524",
    "userId": "1",
    "comment": "Bad station",
    "station": "Blue",
    "commentId": "1"
}

// Delete all comments
###
DELETE http://localhost:8081/comment/deleteAll
Content-Type: application/json


// Delete comment by id (_id)
###
DELETE http://localhost:8081/comment/deleteById/660418440f135f5d36559d11
Content-Type: application/json

// Get comment by id (_id)
###
GET http://localhost:8081/comment/get/660adeb96ed30e4a5d346524
Content-Type: application/json