###
GET http://localhost:8081/comment/getAll
Content-Type: application/json

###
POST http://localhost:8081/comment/createComment

Content-Type: application/json
{
  "commentId": "1",
  "username": "User1",
  "comment": "Great station",
  "station": "station1"
}

###
DELETE http://localhost:8081/comment/deleteAll
Content-Type: application/json

###
DELETE http://localhost:8081/comment/deleteById/1
Content-Type: application/json