###
GET http://localhost:8081/favorite/getAll
Content-Type: application/json


###
POST http://localhost:8081/favorite
Content-Type: application/json

 {
  "userId": "65f1ec23429de3cae859ebe9",
  "bathroomId": "5",
  "line": "Red",
  "station": "Davisa"
}

// _id must be added
###
PUT  http://localhost:8081/favorite/editFav/65f21e78a42f4e8698876cec
Content-Type: application/json 

{
    "_id":"65f21e78a42f4e8698876cec",
    "userId":"65f1ec23429de3cae859ebe9",
    "bathroomId":"1",
    "line":"Blue",
    "station":"North Andover"
}

//Delete by ID 
###
DELETE http://localhost:8081/favorite/deleteFav/65f24a54a42f4e8698876cf2

// do not need the body becuase I deleted by ID







