

###
GET http://localhost:8081/favorite/getAll
Content-Type: application/json


###
POST http://localhost:8081/favorite
Content-Type: application/json

 {
  "userId": "65f1ec23429de3cae859ebe9",
  "bathroomId": "2",
  "line": "Red",
  "station": "Andrew"
}

// _id must be added
// usse _id to edit and server must be restart and reopen rest file
###
PUT  http://localhost:8081/favorite/editFav/65fc6590b11332fbbe778159
Content-Type: application/json 

{
    "_id":"65fc6590b11332fbbe778159",
    "userId":"65f1ec23429de3cae859ebe9",
    "bathroomId":"2",
    "line":"Blue",
    "station":"Airport "
}

//Delete by ID 
###
DELETE http://localhost:8081/favorite/deleteFav/65fc6590b11332fbbe778159

// do not need the body becuase I deleted by ID


###
DELETE http://localhost:8081/favorite/deleteAll




