

###
GET http://localhost:8081/favorite/getAll
Content-Type: application/json


###
POST http://localhost:8081/favorite/
Content-Type: application/json

 {
  "userId": "1",
  "line": "Red",
  "station": "Andrew"
}

// _id must be added
// usse _id to edit and server must be restart and reopen rest file
###
PUT  http://localhost:8081/favorite/editFav/661766f3accd60c438764139
Content-Type: application/json 

{
    "_id":"661766f3accd60c438764139",
    "userId":"1",
    "line":"Blue",
    "station":"Airport "
}

//Delete by ID 
###
DELETE http://localhost:8081/favorite/deleteFav/661766f3accd60c438764139
Content-Type: application/json
// do not need the body becuase I deleted by ID


###
DELETE http://localhost:8081/favorite/deleteAll




