### Create a new rating
POST http://localhost:8081/rating/createrating
Content-Type: application/json

{
  "username": "user123",
  "rating": "5",
  "station": "station123"
}

### Get all ratings
GET http://localhost:8081/rating/getAllRatings


### Update a rating by ID
PUT http://localhost:8081/rating/update/65fc68e627b0adb0768a2a25
Content-Type: application/json

{
    "_id": "65fc68e627b0adb0768a2a25",  
    "rating": "3",
}

### get a rating by id 
GET http://localhost:8081/rating/get/65fc68e627b0adb0768a2a25

### Delete all ratings
DELETE http://localhost:8081/rating/deleteAll