### Create a new rating
POST http://localhost:8081/rating/createrating
Content-Type: application/json

{
  "ratingId": "abc123",
  "username": "user123",
  "rating": "5",
  "station": "station123"
}

### Get all ratings
GET http://localhost:8081/rating/getAllRatings


### Update a rating by ID
Put http://localhost:8081/rating/update/65f9c8343d10da6ae580c897

Content-Type: application/json

{
  "rating": 4
}

### Delete all ratings
DELETE http://localhost:8081/rating/deleteAll
