### Create a new rating
POST http://localhost:8081/rating/createrating
Content-Type: application/json

{
  "rating": "5",
  "station": "Airport"
}

### Get all ratings
GET http://localhost:8081/rating/getAllRatings


### Update a rating by ID
PUT http://localhost:8081/rating/update/65fc68e627b0adb0768a2a25
Content-Type: application/json

{
    "_id": "65fc68e627b0adb0768a2a25", 
    "rating": "3",
    "station": "station123"
}

### get a rating by id 
GET http://localhost:8081/rating/get/65fc68e627b0adb0768a2a25

### Delete all ratings
DELETE http://localhost:8081/rating/deleteAll

### Get rating by station
GET http://localhost:8081/rating/Airport