###
GET http://localhost:8081/favorite/getAll
Content-Type: application/json


###
POST http://localhost:8081/favorite
Content-Type: application/json

 {
  "userId": null,
  "bathroomId": null,
  "line": null,
  "station": null
}





