### Create a new comment
POST http://localhost:8081/comments/comment/add
Content-Type: application/json

{
    "username": "JoshRaimo",
    "userId": "65e7a9d7470f0a7a65dbae6c",
    "commentContent": "This is a test comment",
    "postId": ""
}

### Get a list of all comments
GET http://localhost:8081/comments/comment
Content-Type: application/json

### Reply to a comment
POST http://localhost:8081/comments/comment/reply/
Content-Type: application/json

{
    "commentContent": "This is a reply to the comment"
}

### Update a comment by id
PUT http://localhost:8081/comments/comment/update/
Content-Type: application/json

{
    "commentContent": "This is an updated comment"
}

### Delete a comment by id
DELETE http://localhost:8081/comments/comment/
Content-Type: application/json

### Get a specific comment by id
GET http://localhost:8081/comments/comment/
Content-Type: application/json

### Find comments by postId
GET http://localhost:8081/comments/comment/getCommentById/
Content-Type: application/json

### Get all comments
GET http://localhost:8081/comment/getAll
Content-Type: application/json