POST http://localhost:8081/user/signup
Content-Type: application/json 

{
    "username" : "JoshRaimo",
    "email" : "Joshraimo@gmail.com",
    "password" : "josh1234"
}

###

POST http://localhost:8081/user/login
Content-Type: application/json 

{
    "username" : "JoshRaimo",
    "password" : "josh1234"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###

POST http://localhost:8081/user/EditUser
Content-Type: application/json 

{
    "userId" : "65e7a816470f0a7a65dbae58",
    "username" : "Josh Edit",
    "password" : "josh12345"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "65e7a816470f0a7a65dbae58"
}

###
POST  http://localhost:8081/user/deleteAll